name: Daily Checklist v3
on:
  workflow_dispatch:
  schedule:
  # Updates at 5am everyday (when a new day starts in ACNH) – https://crontab.guru 
  - cron: 0 5 * * *

jobs:
  daily_standup:
    name: Daily Tasklist Issue
    runs-on: ubuntu-latest
    steps:

    - name: Today's date
      run: echo "TODAY=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

    # Generates and pins new standup issue, closes previous, writes linking comments, and assigns to all assignees in list
    - name: Daily Checklist 🕔
      uses: imjohnbo/issue-bot@v3
      with:
        assignees: "fluteds"
        labels: "daily checklist"
        title: Daily ACNH Checklist 🕔
        body: |-
          ## 🌲 ACNH Checklist for ${{ env.TODAY }}
          :wave: Hi, {{#each assignees}}@{{this}}{{#unless @last}}, {{/unless}}{{/each}}! Here's your daily checklist.
          Resets at 🕔 **`5:00 am`** local time.
          * [ ] Check in at the Nook Stop (300 Nook Miles per day after your first 6 days)
          * [ ] Shop the Nook Stop for new special catalog items and fence recipes
          * [ ] Shop at Nook’s Cranny and the Able Sisters’
          * [ ] Complete the first 5 Nook Miles+ missions of the day for 2x bonus
          * [ ] Find your island’s 4 fossils
          * [ ] Find your island’s DIY Recipe message in a bottle
          * [ ] Find your island’s glowing money spot for 💰1,000 Bells. (Optional: Re-plant money in the spot to grow a “money tree" to multiply your investment!)
          * [ ] Harvest resources
            * [ ] Rocks (materials — including up to 💰16,000 Bells from one rock)
            * [ ] Trees
              * [ ] Wood
              * [ ] Fruits (grow every three days after they were last picked)
              * [ ] Furniture, ~💰1,000 Bells, and/or wasps from cedar/hardwood trees
        pinned: false
        close-previous: true
        linked-comments: false
